# Generated by Django 4.1.7 on 2023-05-01 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamehubs', '0002_game_creator_game_name_game_rating_score_gamereview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='score',
            new_name='points',
        ),
        migrations.AddField(
            model_name='gamereview',
            name='review',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
