# Generated by Django 4.1.7 on 2023-05-01 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamehubs', '0003_rename_score_score_points_gamereview_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamereview',
            name='review',
        ),
    ]
