# Generated by Django 4.1.7 on 2023-05-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamehubs', '0004_remove_gamereview_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamereview',
            name='review',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
