# Generated by Django 4.1.7 on 2023-05-01 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamehubs', '0005_gamereview_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamereview',
            name='review',
            field=models.TextField(default=''),
        ),
    ]
