# Generated by Django 4.1.7 on 2023-05-02 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamehubs', '0008_alter_gamereview_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
