# Generated by Django 4.1.7 on 2023-05-02 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamehubs', '0010_highscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='highest_score',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='HighScore',
        ),
    ]
